import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-4.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from '@/components/TransitionEffect';

export default function Home() {
  return (
    <>
      <Head>
        <title>GUIK - PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <TransitionEffect />
      
     <main className= 'flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:p-16 sm:pt-8'>
         <div className="flex items-center justify-between w-full lg:flex-col">
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="Guik" className="w-full h-auto lg:hidden md:inline-block md:w-full" priority         
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"/>
            </div>
            <div className = 'w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>          
              <AnimatedText text="Guilherme Munhos Desenvolvedor Full Stack" className='!text-6xl !text-left
              xl:!text-5xl lg:!text-center md:!text-5xl sm:!text-3xl
              '/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs' >
                Meu nome é Guilherme Munhos, mas pode me chamar de Guik! Tenho 22 anos e sou Estudante de Bacharelado em Ciência da Computação.
               Iniciei minha jornada na programação durante a adolescência e estou retornando aos estudos agora com renovado entusiasmo. Possuo conhecimentos em Python, JavaScript, ReactJS, Node.js, HTML e CSS. Experiência em projetos pessoais e colaborativos, demonstrando criatividade e resolução de problemas. Busco contribuir com soluções inovadoras e aprender constantemente.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/cv.pdf" target={"_blank"} className="flex items-center bg-dark text-light dark:bg-light p-2.5 px-6 
                rounded-lg text-lg fonte-semibold hover:bg-light hover:text-dark border-2 
                border-solid boder-trasparent hover:border-dark  dark:text-dark
                 hover:dark:border-light hover:dark:bg-dark hover:dark:text-light
                 md:p-2 md:px-4 md:text-base
                 " download={true}>
                  CV<LinkArrow className={("w-6 ml-1")} />
                  </Link>
                <Link href="mailto:gui.mbmattos@gmail.com" target={"_blank"} className="ml-4 text-lg font-medium 
                capitalize text-dark dark:text-light underline md:text-base">
                  Contato</Link>
              </div>
            </div>
         </div>
          </Layout>
          <HireMe />
          <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
            <Image src={lightBulb} alt="Guik" className='w-full h-auto'/>
          </div>
     </main>
    </>
  )
}
